services:
  crazydayz.shop:
    image: crazydayz.shop
    build:
      context: .
      dockerfile: CrazyDayZ.Shop/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/Certificates/https.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/app/Certificates/https.key
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ./data:/app/data
      - ./Certificates:/app/Certificates  

volumes:
  db_data: {}
